version: '2'

networks:
  frontend:
  backend:

volumes:
  db-data:
  etherpad-data:

services:

  portal:
    build: ./portal
    env_file: ./docker-common.env
    networks:
      - frontend
    volumes:
      - ./hpi-quotedb-static:/mnt/hpi-quotedb-static
    ports:
      - 80:80

  frame:
    build: ./frame
    env_file: ./docker-common.env
    networks:
      - frontend
    environment:
      # all of those will appear in the toplevel navigation in the order of
      # their number suffix. pattern is label|URL
      - LINK0=Home|/
      - LINK1=180|/180/
      - LINK2=120|/120/
      - LINK3=Etherpad|/etherpad/
      - LINK4=Redmine|https://student.hpi.uni-potsdam.de/redmine/
      - LINK5=Zitate|/quotedb/
      - LINK6=Geocaching|/geocaching
      - LINK7=FSR|https://myhpi.de/fsr/

      # similar to the links, except those go into the 
      # clubs dropdown. same pattern.
      - CLUB0=Zeitungs-Klub|/klub/zeitung
      - CLUB1=Kochklub|/klub/kochen
      - CLUB2=A capella|/klub/acappella
      - CLUB3=Filmklub|/klub/film
      - CLUB4=Connect-Klub|http://hpi.de/connect/start.html
    volumes:
      - ./frame:/var/www/html
    ports:
      - 8000:80

# https://hub.docker.com/_/mysql/
  maindb:
    image: mysql
    networks:
      - backend
    env_file: ./docker-common.env
    volumes:
      - "db-data:/var/lib/mysql"

# https://hub.docker.com/_/wordpress/
  wordpress_filmklub:
    build: ./wordpress
    links:
      - maindb:mysql
    networks:
      - frontend
      - backend
    ports:
      - 8001:80
    env_file: ./docker-common.env
    environment:
      - WORDPRESS_PATH=/klub/film
      - WORDPRESS_DB_NAME=wordpress_filmklub

# https://hub.docker.com/_/wordpress/
  wordpress_zeitungsklub:
    build: ./wordpress
    links:
      - maindb:mysql
    networks:
      - frontend
      - backend
    ports:
      - 8002:80
    env_file: ./docker-common.env
    environment:
      - WORDPRESS_PATH=/klub/zeitung
      - WORDPRESS_DB_NAME=wordpress_zeitungsklub

# https://hub.docker.com/_/wordpress/
  wordpress_acappella:
    build: ./wordpress
    links:
      - maindb:mysql
    networks:
      - frontend
      - backend
    ports:
      - 8003:80
    env_file: ./docker-common.env
    environment:
      - WORDPRESS_PATH=/klub/acappella
      - WORDPRESS_DB_NAME=wordpress_acappella

# https://hub.docker.com/r/tvelocity/etherpad-lite/
  etherpad:
    image: tvelocity/etherpad-lite
    networks:
      - frontend
      - backend
    env_file: ./docker-common.env
    environment:
      - ETHERPAD_ADMIN_PASSWORD=lkskw929djdnd
      - ETHERPAD_ADMIN_USER=admin
      - ETHERPAD_PORT=8000
      - ETHERPAD_DB_NAME=etherpad
      - MYSQL_PORT_3306_TCP_ADDR=maindb
    ports:
      - 8004:8000
    volumes:
      - "etherpad-data:/opt/etherpad-lite/var"
    links:
      - maindb:mysql

  onehundredandtwenty:
    image: nginx
    networks:
      - frontend
    ports:
      - 8005:80
    volumes:
      - ./onehundredandtwenty:/usr/share/nginx/html

  onehundredandeighty:
    image: nginx
    networks:
      - frontend
    ports:
      - 8006:80
    volumes:
      - ./onehundredandeighty:/usr/share/nginx/html

  quotedb:
    build: ./hpi-quotedb
    env_file: ./docker-common.env
    environment:
      - QUOTEDB_DB_NAME=hpiquotedb
      - QUOTEDB_DB_HOST=maindb
      - QUOTEDB_DB_USER=root
      - QUOTEDB_SERVER_BASE_PATH=quotedb/
      - DJANGO_SETTINGS_MODULE=hpi_quotedb.settings.production
    networks:
      - frontend
      - backend
    ports:
      - 8007:8000
    volumes:
      - ./hpi-quotedb:/usr/src/app
      - ./hpi-quotedb-static:/usr/src/app/hpi_quotedb/static
    links:
      - maindb:mysql

